### ISSUE TITLE
fix package build errors

### ISSUE THREAD

**Issue by mathause** [MESMER-group/mesmer#102]
Running
```bash
python setup.py sdist bdist_wheel --universal
twine check dist/mesmer*

```
yields the following errors:
```
Checking dist/mesmer_emulator-0.8.2-py2.py3-none-any.whl: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 3: Warning: Inline strong start-string without end-string.
Checking dist/mesmer-emulator-0.8.2.tar.gz: FAILED
  `long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 3: Warning: Inline strong start-string without end-string.
```

and indeed this looks funky: https://pypi.org/project/mesmer-emulator/0.8.1/ - does it need to be rst? Or another `long_description_content_type="text/x-rst"`?

However, I think this should not prevent us from publishing mesmer.

**Comment by znicholls** [comment]
> 1. Somehow @znicholls managed to publish mesmer anyway - do you still remember how?

I think I used an old version so don't think that trick will work anymore

**Comment by znicholls** [comment]
> I guess this should rather be avoided

absolutely

> good Idea - we can now do `.. include:: ../../README.rst` in the docs (index.rst)

Super nice
