### ISSUE TITLE
unstructured grid

### ISSUE THREAD

**Issue by mathause** [MESMER-group/mesmer#105]
This issue is relevant for  #65

---

Internally mesmer uses an unstructured grid. That is the lat and lon coords are not 2D but along a vector. When we start using xarray internally we need to name the non-coordinate dimension of the vector. @leabeusch suggests to use `"gp"` (for gridpoint). The most likely alternative would be `"cell"` (see details).

<details>

This is what some other models do:

- ICON: `cell`
- MPAS: `nCells`
- CAM with unstructured grid(?) (CAMSE?): `ncol`
- CLM (used internally only): `column` and `gridcell`
- AWI ocean model: `ncells`

</details>

Example:

```python
import xarray as xr
xr.set_options(display_style="text")

lat = [0.5, 0.5, 1.5, 1.5]
lon = [0.5, 1.5, 0.5, 1.5]
data = [0.5, 0.7, 0.8, 0.2]

ds = xr.Dataset(
    data_vars=dict(data=("gp", data)),
    coords={"lon": ("gp", lon), "lat": ("gp", lat)}
)
```

and the repr would look like
```
<xarray.DataArray 'data' (gp: 4)>
array([0.5, 0.7, 0.8, 0.2])
Coordinates:
    lon      (gp) float64 0.5 1.5 0.5 1.5
    lat      (gp) float64 0.5 0.5 1.5 1.5
Dimensions without coordinates: gp
```

- Note: I would not go for a `MultiIndex` because (i) it brings its own set of problems (ii) it should no longer be necessary after the index refactor of xarray (which is actually finally underway) (iii) we probably seldom need to select individual grid points from the 

- Obviously the array has more dimensions, likely `"time"` and `"member"` (or `"realization"`). 
<details>

```
Dimensions:  (member, time, gp)
Coordinates:
    time (time)
    lon  (gp)
    lat  (gp)
Dimensions without coordinates: member, gp
```
</details>

- xarray does not support two dimensions with the same name. Therefore we need new names for the geo distance matrix and the correlation matrix. We thought to subscript `"gp"`, `"lon"`, and `"lat"` with `"_i"`, and `"_j"`:

<details>

```python
geodist = xr.Dataset(
    data_vars=dict(
        dist=(("gp_j", "gp_i"), [
        [0.5, 0.7, 0.8, 0.2],
        [0.5, 0.7, 0.8, 0.2],
        [0.5, 0.7, 0.8, 0.2],
        [0.5, 0.7, 0.8, 0.2]
        ])
    ),
    coords={
        "lon_j": ("gp_j", lon),
        "lat_j": ("gp_j", lat),
        "lon_i": ("gp_i", lon),
        "lat_i": ("gp_i", lat)
    }
)
```
</details>

I.e. the array would look like:
```
<xarray.Dataset>
Dimensions:  (gp_i: 4, gp_j: 4)
Coordinates:
    lon_j    (gp_j) float64 0.5 ...
    lat_j    (gp_j) float64 0.5 ...
    lon_i    (gp_i) float64 0.5 ...
    lat_i    (gp_i) float64 0.5 ...
Dimensions without coordinates: gp_i, gp_j
Data variables:
    dist     (gp_j, gp_i) float64 0.5 ...
```

**Comment by leabeusch** [comment]
Just to follow up on this one more time: seems you all do have nice arguments for `"cell"` over `"gp"` -> consider me convinced of `"cell"` too. 

> Realisation (and if you want to use american spelling I will live) 

Funny that this is coming up already again (@mathause & I had a moderately important discussion about American vs British English in the context of a comma a few weeks ago). I think we may actually have to make a decision on the type of English we use sometimes soonish. ^^

& more importantly, on the `"realization"` vs `"member"` topic: I see @yquilcaille's point as long as it's the actual ESM output. But for the emulations we generate, but I find `"realization"` for the inidivdual emulations a lot more descriptive, as they are realizations of a stochastic process... & the part about the full id, I also see advantages for clear ESM run identification but it feels like a bit a strange overhead for the emulations? & are these member id's even defined outside of CMIP experiments? On the other hand: it would probably also be very counterintuitive to have different naming conventions for the ESM simulations & the emulations.

**Comment by mathause** [comment]
Yes, I am not always consistent in my choice of dialect.

I did just go check the [cmip6 definitions](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit) (see note 8). The whole thing is the `variant_label = "r1i1p1f1"` and

> For a given experiment, the `realization_index`, `initialization_index`, `physics_index`, and `forcing_index` are used to uniquely identify each simulation of an ensemble of runs contributed by a single model.
