### ISSUE TITLE
config state & default config

### ISSUE THREAD

**Issue by mathause** [MESMER-group/mesmer#112]
Currently a config state is passed as a param to each function. Also there is no default configuration (or is there?). Can we avoid `cfg` entirely? If not here are some projects where we could get inspiration from:

- https://docs.oggm.org/en/stable/getting-started.html
- https://docs.dask.org/en/stable/configuration.html

Of course the difficult part is to decide which info should be part of the config and what is passed as arguments.

**Comment by leabeusch** [comment]
Just a quick information: another issue about this has already been opened a few months ago by @znicholls : #34 -> once you / we've worked out a solution for this, we should close them both.
