### ISSUE TITLE
Apply extract method to `train_gt_ic_LOWESS`

### ISSUE THREAD

**Issue by znicholls** [MESMER-group/mesmer#146]
The function `train_gt_ic_LOWESS` is too long (see code smells e.g. https://refactoring.guru/smells/long-method)

To fix that, we need to split it into multiple, smaller methods which are self describing (a technique known as extract method, see https://refactoring.guru/extract-method). In the process, it will also be possible to remove most of (if not all the) comments (see code smell https://refactoring.guru/smells/comments).

**Comment by mathause** [comment]
I'd argue that this has been done in #193
