### ISSUE TITLE
test_calibrate_mesmer_and_draw_realisations.py is empty?

### ISSUE THREAD

**Issue by mathause** [MESMER-group/mesmer#148]
I just saw that [test_calibrate_mesmer_and_draw_realisations.py](https://github.com/MESMER-group/mesmer/blob/master/tests/integration/test_calibrate_mesmer_and_draw_realisations.py) is empty. @znicholls I assume that is not intentional?

**Comment by znicholls** [comment]
I think the idea was to add it at some point but we just test them
separately now maybe? Can you see where it was added? I might have renamed
a file and somehow not deleted the old one
