### ISSUE TITLE
micro-optimization: use np.sum instead of sum

### ISSUE THREAD

**Issue by mathause** [MESMER-group/mesmer#154]
Using `sum(data)` is much slower than `np.sum(data)` or `data.sum()`.

- `create_emus_OLS_each_gp_sep`:

https://github.com/MESMER-group/mesmer/blob/3892e764dd80416137a0bf584f316aa48ca1e11b/mesmer/create_emulations/create_emus_lt.py#L202

Note: would be superseded by #155

- `create_emus_lv_OLS`:

https://github.com/MESMER-group/mesmer/blob/3892e764dd80416137a0bf584f316aa48ca1e11b/mesmer/create_emulations/create_emus_lv.py#L273

Note: would be superseded by #156

- There may be more

**Comment by nikhilnarla** [comment]
Hi, @mathause Looks like we need to replace sum with np.sum here.
Are we supposed to make this change just for the files under [create_emulations]? Please let me know and if my understanding is correct, please assign it to me. :)

**Comment by mathause** [comment]
Correct! AFAIK these are the only two places where `sum` is still used. No need to assign it - just open a PR if you are interested to work on it.

Out of curiosity - what is your interest in MESMER?

**Comment by nikhilnarla** [comment]
Hi, I created a PR, please check and let me know if I  need to make any changes. Also it looks like a very interesting project given the impact it is going to have. Achieving the same performance for month-wise computation rather than annual would make it much more accurate.

**Comment by mathause** [comment]
Thanks! Note that there is a MESMER-based monthly emulator, that is unfortunately not yet included in the repository: [Nath et al., 2022](https://esd.copernicus.org/articles/13/851/2022/esd-13-851-2022.html).
