### ISSUE TITLE
Create test for training MESMER + creating MESMER bundle

### ISSUE THREAD

**Issue by leabeusch** [MESMER-group/mesmer#26]
As part of this test `examples/train_create_emus_automated.py` will be brought back to better shape. Meaning: a script very similar to the current `train_create_emus_automated.py` will be moved to the `tests` folder and everything concerning saving the MESMER bundle can potentially be removed again from ` train_create_emus_automated.py`. Alternatively, we could consider leaving saving the bundle inside of the `examples` script as well... in that case, we'd need to find a cleaner solution for where to save the bundle though.

**Comment by leabeusch** [comment]
@znicholls do you agree that we can close this issue now that we merged #52? We didn't follow everything in detail that we said here but the general idea seems close enough.

**Comment by znicholls** [comment]
Yep
