### ISSUE TITLE
add version 0.1?

### ISSUE THREAD

**Issue by mathause** [MESMER-group/mesmer#31]
Could be good to release a version/ tag - so you still know which version you used for the paper.

**Comment by leabeusch** [comment]
As discussed: would be great if the paper version could be 0.8.0. Not sure if it's worth to do one already before that... Probably not?

**Comment by znicholls** [comment]
Yep and putting it on pypi and conda at the same time

**Comment by mathause** [comment]
Yes, but note that AFAIK unfortunately the name mesmer is already taken on pypi - we'll probably need to name it something else on pypi (similar to scikit?). E.g. `pip install mesmer-emulator`?
