### ISSUE TITLE
Separate better what belongs together in load_regs_ls_wgt_lon_lat () and in extract_land()

### ISSUE THREAD

**Issue by leabeusch** [MESMER-group/mesmer#36]
As @znicholls pointed out in #23: currently I need to decide over which regions I want to be able to aggregate at the very beginning and those are loaded in together with the land-sea mask through `load_regs_ls_wgt_lon_lat()` and additional information is added to the region dictionary by the function `extract_land()`. It would make more sense to separate the two things, since the land-sea information needs to be available before MESMER can be trained but the region information is only relevant if the data should be spatially aggregated during the analysis. I.e., we should create separate functions for the land-sea part and for the region part. 

This issue is not too high on the priority list though and can be dealt with once more relevant issues are out of the way.

**Comment by mathause** [comment]
Given I removed this functionality in #235 I think this issue can be closed.
