### ISSUE TITLE
optimize `_generate_fourier_series_np`

### ISSUE THREAD

**Issue by mathause** [MESMER-group/mesmer#410]
I think the mesmer_m part can be optimized. For example `generate_fourier_series_np`.

1. I think the name is not optimal. That should probably be `estimate` or `predict` instead of `generate`.
2. The code can be sped up by vectorizing it:
   ```python
       # TODO:
       # - can remove n from the inputs as it's coeffs.shape / 4
       # - rename n to order (as n is not a good name, but see above)
       # - why is there a "-2" for the number of coeffs?
       # - can this be rewritten as fft? (no -> as the amplitude varies with x)
   
       coeffs_ = coeffs.reshape(-1, 4)
   
       k = np.arange(coeffs_.shape[0])[:, np.newaxis]
   
       alpha = 2 * np.pi * k * (mon % 12 + 1) / 12
   
       predictions = np.sum(
           (coeffs_[:, 0:1] * x + coeffs_[:, 1:2]) * np.sin(alpha)
           + (coeffs_[:, 2:3] * x + coeffs_[:, 3:4]) * np.cos(alpha),
           axis=0,
       )
   
       return predictions
   ```

---

And similar for other functions.

**Comment by veni-vidi-vici-dormivi** [comment]
After playing with it for a while I actually think the name is accurate. The real data is not a Fourier series so estimate and predict is not what we really do. We generate a Fourier series for the estimated or predicted coefficients which are estimated/predicted in `fit_fourier_series_np`.

**Comment by mathause** [comment]
I thought about if it makes sense to save the `coeffs` as 2D array, i.e. with dims `order x coeffs` and size `order x 4`. This could help with interpretation.
