### ISSUE TITLE
rethinking `Expression` class?

### ISSUE THREAD

**Issue by mathause** [MESMER-group/mesmer#528]
In #525 we saw that generating a distribution with covariates from a string can be brittle. @veni-vidi-vici-dormivi suggested a potential way forward (I'll post that below). I think it's better to discuss this in a separate issue so I'll paste the comment below and we can discuss here.

**Comment by mathause** [comment]
Ok we were doing the same so let's close this issue in favor of #527

**Comment by veni-vidi-vici-dormivi** [comment]
Sorry 😅
