### ISSUE TITLE
Finish removing left-over unnecessary emulation parts from calibration function and test

### ISSUE THREAD

**Issue by leabeusch** [MESMER-group/mesmer#66]
- Work through all “TODO remove” comments in the respective scripts
- Rewrite code slightly to be able to remove the `emus_gt` variable from `_calibrate_and_draw_realisations()`
- Rename `_calibrate_and_draw_realisations()` to `_calibrate()` 
- … (whatever else I forgot to mention so far)

**Comment by mathause** [comment]
Part of this was done in #246 and #248
