### ISSUE TITLE
linting of versioneer.py

### ISSUE THREAD

**Issue by mathause** [MESMER-group/mesmer#83]
`versioneer.py` is not correctly formated, so its changed when calling `isort .` and `black .` (which I usually do). We can either re-format it or exclude it from these tools. I'd vote for (1). Anything speaking against this @znicholls ? (e.g. you can no longer diff it to the original version but I don't know if this is important.

**Comment by znicholls** [comment]
I've always gone for (2) just so it's clear that nothing has changed from the original. I don't mind though, either is fine
